swagger: '2.0'
info:
  title: Authorized Audience Manager API
  description: |
    In order to acces those endpoints, you need to **authenticate**.
    <a href="../../getting_started.html">Here is a guide on how to do it.</a>
  version: 'auto'
host: your-instance-name.piwik.pro
basePath: /
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
definitions:
  Audience:
    $ref: ./definitions/audience.yaml
  ExportData:
    $ref: ./definitions/export_data.yaml
  ExportAttribute:
    $ref: ./definitions/export_attribute.yaml
  AudienceCount:
    $ref: ./definitions/audience_count.yaml
  ProfileDetails:
    $ref: ./definitions/profile_details.yaml
  ProfileList:
    $ref: ./definitions/profile_list.yaml
parameters:
  WebsiteId:
    name: website_id
    in: query
    type: string
    format: uuid
    description: App ID (previously Website ID).
    required: true
    example: '0fdd8cc2-93b1-428c-8373-97a452f5b10'
paths:
  /api/audiences/v1/audiences/:
    $ref: ./paths/audiences_list.yaml
  /api/audiences/v1/profiles/:
    $ref: ./paths/profiles_export.yaml
  /api/audiences/v1/profiles/get:
    $ref: ./paths/profiles_get.yaml
