openapi: '3.0.0'
x-api-category: Tag Manager
info:
    title: Tag Manager API
    version: '1.0'
    description: |
        # Tag template options
        - It is essential to treat the template options as a cohesive object.
        - When using a PATCH request, remember to include all the attributes you want to be set.

        # Deprecations and changes

        <details>
        <summary>Deprecated tags</summary>
        The tags listed below are marked as deprecated and will not be supported soon.
        We strongly discourage using them.

        | Deprecated tags               |
        |---                            |
        | Custom tag (synchronous)      |
        | A/B Tasty tag                 |
        | Clicktale Tracking Code tag   |
        | DoubleClick Conversion tag    |
        | Optimizely tag                |
        | Visual Website Optimizer tag  |

        </details>

        <details>
        <summary>Renamed tags</summary>
        The following tags have been rebranded. However, their template attribute value remained the same due to maintaining backward compatibility.

        | Old tag name                      | New tag name          |
        |---                                |---                    |
        | Facebook Retargeting Pixel tag    | Meta Pixel tag        |
        | DoubleClick Floodlight Sales tag  | Floodlight Sales tag  |
        | DoubleClick Floodlight Counter tag| Floodlight Counter tag|

        </details>

        # Asynchronous operations

        - Some actions result in asynchronous operations. In such cases, the API will return a 202 status code with operation id in `relationships` object.
        - The operation status can be checked by sending a GET request to `/api/tag/v1/{app_id}/operations/{operation_id}` URL.
        - Operation can be in one of the following states:
            - `created` - the operation has been created
            - `started` - the operation has been started and is currently in progress
            - `completed` - the operation been completed successfully and the result is available
            - `failed` - the operation has failed
        - Operations can be distinguished by the `operation_type` attribute.
        - There can only be 1 operation of a given type (in state `started` or `created`) for a given resource (app) at a time.
security:
    - BearerAuth: []

servers:
    - url: https://example.piwik.pro

paths:
    /api/tag/v1/{app_id}/tags:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'

        get:
            x-api-publish: true
            summary: List of tags
            tags:
                - Tags
            description: |
                ### JSON API compatibility divergence

                #### Filters
                In JSON API standard (https://jsonapi.org/recommendations/#filtering) one can request elements with multiple
                filter values by simply providing them separated by coma:

                `tags?filter[template]=piwik,adroll`

                This notation will not work here. You can achieve this functionality by providing multiple filters for the same parameter:

                `tags?filter[template][]=piwik&filter[template][]=adroll`
            parameters:
                - $ref: 'common/api/common_request_parameters.json#/components/parameters/page[limit]'
                - $ref: 'common/api/common_request_parameters.json#/components/parameters/page[offset]'
                - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/filter[name]'
                - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/filter[is_active]'
                - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/filter[tag_type]'
                - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/filter[template]'
                - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/filter[is_prioritized]'
                - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/sort'
            responses:
                '200':
                    description: List of tags
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'tags/schema/list/tags_list_response_schema.json'
                            example:
                                $ref: 'tags/example/list/tags_list_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
        patch:
            x-api-publish: true
            summary: Edit tags order
            tags:
                - Tags
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'tags/schema/list/tags_edit_order_request_schema.json'
                        example:
                            $ref: 'tags/example/list/tags_edit_order_request_example.json'
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'

        post:
            x-api-publish: true
            summary: Create tag
            tags:
                - Tags
            description: |
                See more details about API changes: <a href="#section/Deprecations-and-changes">Deprecations and changes</a>
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'tags/schema/create/tags_create_request_schema.json'
                        examples:
                            Custom tag:
                                description: Custom tag without triggers
                                externalValue: 'tags/example/create/tags_create_request_example.json'
                            Custom tag with triggers:
                                description: Custom tag with triggers
                                externalValue: 'tags/example/create/tags_create_request_example_with_triggers.json'
                            A/B tasty template:
                                description: A/B tasty template
                                externalValue: 'tags/example/create/tags_create_request_example_ab_tasty.json'
            responses:
                '201':
                    description: Tag data
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'tags/schema/create/tags_create_response_schema.json'
                            example:
                                $ref: 'tags/example/get/tags_get_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'

    /api/tag/v1/{app_id}/tags/{tag_id}/triggers:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'
            - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/tag_id'
        get:
            x-api-publish: true
            summary: List of triggers for a given tag
            tags:
                - Tags
            parameters:
                - $ref: 'common/api/common_request_parameters.json#/components/parameters/page[limit]'
                - $ref: 'common/api/common_request_parameters.json#/components/parameters/page[offset]'
                - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/filter[name]'
                - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/filter[trigger_type]'
                - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/sort'
            responses:
                '200':
                    description: List of triggers for a given tag
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'triggers/schema/list/triggers_list_response_schema.json'
                            example:
                                $ref: 'triggers/example/list/triggers_list_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'

    /api/tag/v1/{app_id}/tags/{tag_id}:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'
            - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/tag_id'
        get:
            x-api-publish: true
            summary: Get tag
            tags:
                - Tags
            responses:
                '200':
                    description: Tag data
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'tags/schema/get/tags_get_response_schema.json'
                            example:
                                $ref: 'tags/example/get/tags_get_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'

        patch:
            x-api-publish: true
            summary: Edit tag
            tags:
                - Tags
            description: |
                See more details about API changes: <a href="#section/Deprecations-and-changes">Deprecations and changes</a>
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'tags/schema/edit/tags_edit_request_schema.json'
                        example:
                            $ref: 'tags/example/edit/tags_edit_request_example.json'
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'

        delete:
            x-api-publish: true
            summary: Delete tag
            tags:
                - Tags
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'

    /api/tag/v1/{app_id}/tags/{tag_id}/copy:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'
            - $ref: 'tags/api/tags_request_parameters.json#/components/parameters/tag_id'

        post:
            x-api-publish: true
            summary: Copy tag
            tags:
                - Tags
            description: |
                This action results in asynchronous operation. See more: <a href="#section/Asynchronous-operations">Asynchronous operations</a>
            responses:
                '202':
                    description: Operation data with new (copied) tag identifier
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'tags/schema/copy/tags_copy_response_schema.json'
                            example:
                                $ref: 'tags/example/copy/tags_copy_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'tags/schema/copy/tags_copy_request_schema.json'
                        example:
                            $ref: 'tags/example/copy/tags_copy_request_example.json'

components:
    securitySchemes:
        $ref: 'common/api/common_security_schemes.json#/components/securitySchemes'
