openapi: '3.0.0'
x-api-category: Tag Manager
info:
    title: Tag Manager API
    version: '1.0'
    description: |
        # Asynchronous operations

        - Some actions result in asynchronous operations. In such cases, the API will return a 202 status code with operation id in `relationships` object.
        - The operation status can be checked by sending a GET request to `/api/tag/v1/{app_id}/operations/{operation_id}` URL.
        - Operation can be in one of the following states:
            - `created` - the operation has been created
            - `started` - the operation has been started and is currently in progress
            - `completed` - the operation been completed successfully and the result is available
            - `failed` - the operation has failed
        - Operations can be distinguished by the `operation_type` attribute.
        - There can only be 1 operation of a given type (in state `started` or `created`) for a given resource (app) at a time.

security:
    - BearerAuth: []

servers:
    - url: https://example.piwik.pro

paths:
    /api/tag/v1/{app_id}/triggers:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'

        get:
            x-api-publish: true
            summary: List of triggers
            tags:
                - Triggers
            description: |
                ### JSON API compatibility divergence

                #### Filters
                In JSON API standard (https://jsonapi.org/recommendations/#filtering) one can request elements with multiple
                filter values by simply providing them separated by coma:

                `triggers?filter[trigger_type]=click,event`

                This notation will not work here. You can achieve this functionality by providing multiple filters for the same parameter:

                `triggers?filter[trigger_type][]=click&filter[trigger_type][]=event`
            parameters:
                - $ref: 'common/api/common_request_parameters.json#/components/parameters/page[limit]'
                - $ref: 'common/api/common_request_parameters.json#/components/parameters/page[offset]'
                - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/filter[name]'
                - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/filter[trigger_type]'
                - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/sort'
            responses:
                '200':
                    description: List of triggers
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'triggers/schema/list/triggers_list_response_schema.json'
                            example:
                                $ref: 'triggers/example/list/triggers_list_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'

        post:
            x-api-publish: true
            summary: Create trigger
            tags:
                - Triggers
            responses:
                '201':
                    description: Trigger data
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'triggers/schema/create/triggers_create_response_schema.json'
                            example:
                                $ref: 'triggers/example/create/triggers_create_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'triggers/schema/create/triggers_create_request_schema.json'
                        example:
                            $ref: 'triggers/example/create/triggers_create_request_example.json'

    /api/tag/v1/{app_id}/triggers/{trigger_id}:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'
            - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/trigger_id'

        get:
            x-api-publish: true
            summary: Get trigger
            tags:
                - Triggers
            responses:
                '200':
                    description: Trigger data
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'triggers/schema/get/triggers_get_response_schema.json'
                            example:
                                $ref: 'triggers/example/get/triggers_get_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'

        patch:
            x-api-publish: true
            summary: Edit trigger
            tags:
                - Triggers
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'triggers/schema/edit/triggers_edit_request_schema.json'
                        example:
                            $ref: 'triggers/example/edit/triggers_edit_request_example.json'

        delete:
            x-api-publish: true
            summary: Delete trigger
            tags:
                - Triggers
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'

    /api/tag/v1/{app_id}/triggers/{trigger_id}/copy:
        parameters:
            - $ref: 'common/api/common_request_parameters.json#/components/parameters/app_id'
            - $ref: 'triggers/api/triggers_request_parameters.json#/components/parameters/trigger_id'

        post:
            x-api-publish: true
            summary: Copy trigger
            tags:
                - Triggers
            description: |
                This action results in asynchronous operation. See more: <a href="#section/Asynchronous-operations">Asynchronous operations</a>
            responses:
                '202':
                    description: Operation data with new (copied) trigger identifier
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'triggers/schema/copy/triggers_copy_response_schema.json'
                            example:
                                $ref: 'triggers/example/copy/triggers_copy_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
                '503':
                    $ref: 'common/api/common_error_responses.json#/components/responses/service_unavailable'
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'triggers/schema/copy/triggers_copy_request_schema.json'
                        example:
                            $ref: 'triggers/example/copy/triggers_copy_request_example.json'

components:
    securitySchemes:
        $ref: 'common/api/common_security_schemes.json#/components/securitySchemes'
