swagger: '2.0'

info:
  title: Access Control Api
  version: auto

host: example.piwik.pro
schemes: [https]

paths:
  /api/access-control/v2/entry/{entity_id}:
    get:
      summary: Entity actions
      description: Returns granted permissions (actions) to given entity for current user.
      operationId: get_entity_actions_v2
      produces:
        - application/vnd.api+json
      parameters:
        - $ref: '#/parameters/EntityId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EntityActionsResponse'
        400:
          description: Bad Request
        403:
          description: Forbidden
  /api/access-control/v2/entry/{entity}/action/{action}:
    get:
      summary: Entity actions for users
      description: Returns users with granted permissions (actions) to given entity.
      operationId: get_entities_with_action_v2
      produces:
        - application/vnd.api+json
      parameters:
        - $ref: '#/parameters/Entity'
        - name: action
          in: path
          description: Action of the entity
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EntityActionsForUsers'
        400:
          description: Bad Request
        403:
          description: Forbidden
  /api/access-control/v2/entry/groups/{entity}/{entity_id}:
    get:
      summary: Permission groups
      description: Returns permission groups that have masks which are a subset of permission mask for entries of given type.
      operationId: get_permission_groups_v2
      produces:
        - application/vnd.api+json
      parameters:
        - in: query
          name: limit
          type: integer
          description: Number of results set returned
          default: 10
        - in: query
          name: offset
          type: integer
          description: The number of items to skip before starting to collect the result set
          default: 0
        - $ref: '#/parameters/Entity'
        - $ref: '#/parameters/EntityId'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PermissionGroup'
        400:
          description: Bad Request
        403:
          description: Forbidden
  /api/access-control/v2/entry/group:
    post:
      summary: Permission group set
      description: It sets permission group for given entity (ppms/user or ppms/app).
      operationId: set_permission_group_v2
      parameters:
        -
          name: permission group request
          in: body
          description: set permission group
          required: true
          schema:
            type: object
            properties:
              data:
                $ref: '#/definitions/PermissionGroupSet'
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
        403:
          description: Forbidden
  /api/access-control/v2/global/actions:
    get:
      summary: Global actions
      description: It gets actions without specific entity context for given user.
      operationId: get_GlobalActions_v2
      produces:
        - application/vnd.api+json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GlobalActions'
        400:
          description: Bad Request
        403:
          description: Forbidden

definitions:
  EntityActionsResponse:
    type: object
    properties:
      data:
        allOf:
          -   $ref: '#/definitions/JsonApiResourceObject'
          -   properties:
                attributes:
                  type: object
                  properties:
                    actions:
                      type: array
                      items:
                        type: string
                      description: List of available actions for given entity
    example:
      data:
        type: ppms/permission/entity/actions
        id: 50fca71a-e4a7-4480-a612-a9ffbdf0935f
        attributes:
          actions:
            - view
            - edit
            - publish
            - delete
            - manage

  EntityActionsForUsers:
    type: object
    properties:
      meta:
        type: object
        description: Meta information
        properties:
          total:
            type: integer
            description: Number of records found
      data:
        type: object
        allOf:
          -   $ref: '#/definitions/JsonApiResourceObject'
          -   properties:
                attributes:
                  type: object
                  properties:
                    actions:
                      type: array
                      items:
                        type: string
                      description: List of available actions for given entity
    example:
      meta:
        total: 2
      data:
        -   id: e0180272-d1f5-4bb5-a7d3-0f1a138eacd5
            type: ppms/permission/entity
            attributes:
              entityType: ppms/app
        -   id: ccc9c3a4-fd65-4755-900f-2590460aff44
            type: ppms/permission/entity
            attributes:
              entityType: ppms/app

  PermissionGroup:
    type: object
    properties:
      data:
        allOf:
          -   $ref: '#/definitions/JsonApiResourceObject'
          -   properties:
                attributes:
                  type: object
                  properties:
                    permissions:
                      type: array
                      items:
                        type: string
                      description: List of available actions for given entity
    example:
      -   meta:
            total: 20
      -   data:
            -   type: ppms/permissions/group
                id: 8275cf58-93db-4cda-9d11-7262376c2c72
                attributes:
                  permissions:
                    - no-access
                  group_permissions:
                    permission: Manage
                    group_names:
                      - User group 1
                      - User group 2

  PermissionGroupSet:
    type: object
    properties:
      type:
        type: string
        enum: [ppms/permissions/group]
      attributes:
        type: object
        properties:
          entity:
            type: string
            enum: [ppms/app]
          entityId:
            type: string
            format: uuid
            description: UUIDv4 identifier of given entity
            example: 94445dcb-4da3-4e24-9f7b-c685aacc5a2a
          group:
            type: string
            enum:
              - no-access
              - view
              - edit
              - edit-publish
              - manage
          targetUserId:
            type: string
            format: uuid
            description: UUIDv4 identifier of user which will recieve permissions
            example: 94445dcb-4da3-4e24-9f7b-c685aacc5a2a
    example:
      type: ppms/permissions/group
      attributes:
        entity: ppms/app
        entityId: 50fca71a-e4a7-4480-a612-a9ffbdf0935f
        group: manage
        targetUserId: 8275cf58-93db-4cda-9d11-7262376c2c72

  GlobalActions:
    type: object
    properties:
      data:
        allOf:
          -   $ref: '#/definitions/JsonApiResourceObject'
          -   properties:
                attributes:
                  type: object
                  properties:
                    permissions:
                      type: array
                      items:
                        type: string
                      description: List of global permissions for authorized user
    example:
      data:
        id: ppms/user
        type: ppms/permissions/global
        attributes:
          permissions:
            - delete
            - edit

  JsonApiId:
    type: string
    format: uuid
    description: Resource ID
    example: 985ed9d7-b652-47b8-b9cf-c17d62735261

  JsonApiType:
    type: string
    description: Resource type, unique across whole PPMS
    example: ppms/user

  JsonApiResourceObject:
    type: object
    properties:
      id:
        $ref: '#/definitions/JsonApiId'
      type:
        $ref: '#/definitions/JsonApiType'
      attributes:
        type: object

parameters:
  Entity:
    in: path
    name: entity
    description: entity
    type: string
    required: true
    enum:
      - ppms/app
      - ppms/user

  EntityId:
    in: path
    name: entity_id
    type: string
    format: uuid
    required: true
    description: UUIDv4 identifier of given entity
