swagger: '2.0'
info:
  title: Reporting
  description:
  version: 'auto'
host: account-name.piwik.pro
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/analytics/v1/query/:
    $ref: ./paths/query.yaml
  /api/analytics/v1/sessions/:
    $ref: ./paths/sessions.yaml
  /api/analytics/v1/events/:
    $ref: ./paths/events.yaml
definitions:
  QueryRequest:
    $ref: ./definitions/query_request.yaml
  RawDataRequest:
    $ref: ./definitions/raw_data_request.yaml
