openapi: '3.0.0'
info:
    title: Container Settings API
    version: '1.0'

security:
    - BearerAuth: []

servers:
    - url: https://example.piwik.pro

paths:
    /api/container-settings/v1/app/{app_id}/installation-code:
        parameters:
            - $ref : 'schema/common_request_parameters.json#/components/parameters/app_id'
        get:
            x-api-publish: true
            summary: Get App's installation code
            responses:
                '200':
                    description: OK
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'schema/response/app_container_installation_code_response_schema.json'
                            example:
                                $ref: 'example/app_container_installation_code_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
