openapi: '3.0.0'
x-api-category: Container Settings
info:
    title: Container Settings API
    version: '1.0'

security:
    - BearerAuth: []

servers:
    - url: https://example.piwik.pro

paths:
    /api/container-settings/v1/app/{app_id}/settings:
        parameters:
            - $ref : 'schema/common_request_parameters.json#/components/parameters/app_id'
        get:
            x-api-publish: true
            summary: Get App's container settings
            responses:
                '200':
                    description: OK
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'schema/response/app_container_settings_list_response_schema.json'
                            example:
                                $ref: 'example/app_container_settings_list_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
        patch:
            x-api-publish: true
            summary: Modify App's container settings
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'schema/request/app_container_settings_edit_request_schema.json'
                        example:
                            $ref: 'example/app_container_settings_edit_request_example.json'
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
    /api/container-settings/v1/app/{app_id}/settings/{setting_name}:
        parameters:
            - $ref : 'schema/common_request_parameters.json#/components/parameters/app_id'
            - $ref : 'schema/common_request_parameters.json#/components/parameters/setting_name'
        get:
            x-api-publish: true
            summary: Get the App's container setting
            responses:
                '200':
                    description: OK
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'schema/response/app_container_setting_response_schema.json'
                            examples:
                                'automatic_scroll_tracking':
                                    value:
                                        $ref: 'example/automatic_scroll_tracking_app_container_setting_response_example.json'
                                'container_js_path':
                                    value:
                                        $ref: 'example/container_js_path_app_container_setting_response_example.json'
                                'fpc':
                                    value:
                                        $ref: 'example/fpc_app_container_setting_response_example.json'
                                'static_resources_domain':
                                    value:
                                        $ref: 'example/static_resources_domain_app_container_setting_response_example.json'
                                'tracking_domain':
                                    value:
                                        $ref: 'example/tracking_domain_app_container_setting_response_example.json'
                                'tracking_script_path':
                                    value:
                                        $ref: 'example/tracking_script_path_app_container_setting_response_example.json'
                                'tracking_endpoint_path':
                                    value:
                                        $ref: 'example/tracking_endpoint_path_app_container_setting_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
        delete:
            x-api-publish: true
            summary: Remove the App's container setting
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
        put:
            x-api-publish: true
            summary: Modify App's container setting
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'schema/request/app_container_setting_edit_request_schema.json'
                        example:
                            $ref: 'example/app_container_setting_edit_request_example.json'
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
    /api/container-settings/v1/organization/{organization}/settings:
        parameters:
            - $ref : 'schema/common_request_parameters.json#/components/parameters/organization'
        get:
            x-api-publish: true
            summary: Get list of organization's container settings
            responses:
                '200':
                    description: OK
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'schema/response/organization_container_settings_list_response_schema.json'
                            example:
                                $ref: 'example/organization_container_settings_list_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
        patch:
            x-api-publish: true
            summary: Modify organization's container settings
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'schema/request/organization_container_settings_edit_request_schema.json'
                        example:
                            $ref: 'example/organization_container_settings_edit_request_example.json'
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
    /api/container-settings/v1/organization/{organization}/settings/{setting_name}:
        parameters:
            - $ref : 'schema/common_request_parameters.json#/components/parameters/organization'
            - $ref : 'schema/common_request_parameters.json#/components/parameters/setting_name'
        get:
            x-api-publish: true
            summary: Fetch organization's container setting
            responses:
                '200':
                    description: OK
                    content:
                        application/vnd.api+json:
                            schema:
                                $ref: 'schema/response/organization_container_setting_response_schema.json'
                            example:
                                $ref: 'example/organization_container_setting_response_example.json'
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
        put:
            x-api-publish: true
            summary: Modify organization\'s container setting
            requestBody:
                required: true
                content:
                    application/vnd.api+json:
                        schema:
                            $ref: 'schema/request/organization_container_setting_edit_request_schema.json'
                        example:
                            $ref: 'example/organization_container_setting_edit_request_example.json'
            responses:
                '204':
                    description: No content
                '400':
                    $ref: 'common/api/common_error_responses.json#/components/responses/bad_request_uri_parameter'
                '401':
                    $ref: 'common/api/common_error_responses.json#/components/responses/unauthorized'
                '404':
                    $ref: 'common/api/common_error_responses.json#/components/responses/not_found'
                '500':
                    $ref: 'common/api/common_error_responses.json#/components/responses/internal_server_error'
